name: check

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    # UTC 时间的下午 5 点 30 分，北京时间的凌晨 1 点 30 分
    - cron: "30 17 * * *"

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      GIT_USER_EMAIL: "llswdhh@163.com"
      GIT_USER_NAME: "IabSDocker"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ssh-key: "${{ secrets.COMMIT_KEY }}"
      - name: Find packages
        shell: bash
        run: |
          # git tag
          chmod +x ./check-version.sh
          ./check-version.sh
      - name: Create and push tags
        shell: bash
        run: |
          chmod +x ./create-push-tags.sh
          ./create-push-tags.sh
